# DSCI-633 Lab #6 (python)
# K-Means Algorithm

## Complete find_closest_centroid( )  and 
## Complete calc_centroids( ).

### Name: Ji Woong Kim

In [535]:
# Import all needed libraries
import numpy as np
import pandas as pd
import numpy.matlib
import sys

In [536]:
# upload iris dataset
df = pd.read_csv('iris.csv')
df.columns = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'species']

In [537]:
# Use all records in the dataset withoout classes ('species' column) for cluster analysis
cluster_data = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']].copy(deep=True)

# Sort the dataset by attributes to select the suboptimal starting centroid
cluster_data.sort_values(by=['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'], inplace=True)
cluster_array = np.array(cluster_data)
print(cluster_array)

[[4.3 3.  1.1 0.1]
 [4.4 2.9 1.4 0.2]
 [4.4 3.  1.3 0.2]
 [4.4 3.2 1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.1 1.5 0.2]
 [4.6 3.2 1.4 0.2]
 [4.6 3.4 1.4 0.3]
 [4.6 3.6 1.  0.2]
 [4.7 3.2 1.3 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 3.  1.4 0.3]
 [4.8 3.1 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]
 [4.9 3.  1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [5.  2.  3.5 1. ]
 [5.  2.3 3.3 1. ]
 [5.  3.  1.6 0.2]
 [5.  3.2 1.2 0.2]
 [5.  3.3 1.4 0.2]
 [5.  3.4 1.5 0.2]
 [5.  3.4 1.6 0.4]
 [5.  3.5 1.3 0.3]
 [5.  3.5 1.6 0.6]
 [5.  3.6 1.4 0.2]
 [5.1 2.5 3.  1.1]
 [5.1 3.3 1.7 0.5]
 [5.1 3.4 1.5 0.2]
 [5.1 3.5 1.4 0.3]
 [5.1 3.7 1.5 0.4]
 [5.1 3.8 1.5 0.3]
 [5.1 3.8 1.6 0.2]
 [5.1 3.8 1.9 0.4]
 [5.2 2.7 3.9 1.4]
 [5.2 3.4 1.4 0.2]
 [5.2 3.5 1.5 0.2]
 [5.2 4.1 1.5 0.1]
 [5.3 3.7 1.5 0.2]
 [5.4 3.  4.5 1.5]
 [5.4 3.4 1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.4 3.7 1.5 0.2]
 [5.4 3.9 1.3 0.4]
 [5.4 3.9 1.7 0.4]
 [5.5 2.3 4.  1.3]
 [5.5 2.4 3.

In [538]:
print(cluster_array[0:10])

[[4.3 3.  1.1 0.1]
 [4.4 2.9 1.4 0.2]
 [4.4 3.  1.3 0.2]
 [4.4 3.2 1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.1 1.5 0.2]
 [4.6 3.2 1.4 0.2]
 [4.6 3.4 1.4 0.3]
 [4.6 3.6 1.  0.2]
 [4.7 3.2 1.3 0.2]]


In [539]:
cluster_array.shape[0]

149

In [540]:
cluster_array.shape

(149, 4)

In [541]:
# Calculate Euclidean distance between two observations
def distance(X1, X2):
    return (sum((X1 - X2)**2))**0.5



# Assign each point to its closest centroid
def find_closest_centroid(centroids, cluster_array):
    clusters = []
#### Complete this #########

    for i in range(cluster_array.shape[0]):
        centroidForCluster = 11110
        idx = 0
#         print("cluster>>")
#         print(cluster_array[i])
#         print("<<cluster")
        for j in range(len(centroids)):
#             print("centroid>>")
#             print(centroids[j])
#             print("<<centroid")
            dist = distance( cluster_array[i], centroids[j])
#             print("dist : ", dist)
#             print("centroidForCluster:", centroidForCluster)
            if dist <= centroidForCluster:
                centroidForCluster = dist
                idx = j

        clusters.append(idx)

    return clusters





# Calculate new centroids based on each cluster's mean
def calc_centroids(clusters, cluster_array):
    new_centroids = []

#### Complete this #########

    clusterTotal = [0.0, 0.0, 0.0, 0.0]
    numOfList = [0, 0, 0, 0]
    
    for i in range(len(clusters)):    
        clusterTotal[clusters[i]] = clusterTotal[clusters[i]] + cluster_array[i]
        numOfList[clusters[i]] = numOfList[clusters[i]] + 1
    
#     print(clusterTotal)
#     print(numOfList)
    
    finalCentroid = [0.0, 0.0, 0.0, 0.0]
    for i in range(4):        
        finalCentroid[i] = clusterTotal[i]/ float(numOfList[i])

    return finalCentroid


# Calculate SSE (Sum of the Squared Error) within each cluster
def calc_SSE(clusters, cluster_array):
    sum_squares = []
    cluster_df = pd.concat([pd.DataFrame(cluster_array),
                            pd.DataFrame(clusters, columns=['cluster'])], axis=1)
    for c in set(cluster_df['cluster']):
        current_cluster = cluster_df[cluster_df['cluster']\
                                     ==c][cluster_df.columns[:-1]]
        cluster_mean = current_cluster.mean(axis=0)
        mean_repmat = np.matlib.repmat(cluster_mean, 
                                       current_cluster.shape[0],1)
        sum_squares.append(np.sum(np.sum((current_cluster - mean_repmat)**2)))
    return sum_squares

In [542]:
k = 4
cluster_vars = []

# randomly pick the initial centroid
centroids = [cluster_array[i+2] for i in range(k)]

print(centroids)
# print("---centroids---")
# for i in range(len(centroids)):
#     print(centroids[i])
# print("---centroids---")

print("centroids :", type(centroids[0]))
clusters = find_closest_centroid(centroids, cluster_array)
initial_clusters = clusters
print(initial_clusters)
print(0, round(np.mean(calc_SSE(clusters, cluster_array))))

[array([4.4, 3. , 1.3, 0.2]), array([4.4, 3.2, 1.3, 0.2]), array([4.5, 2.3, 1.3, 0.3]), array([4.6, 3.1, 1.5, 0.2])]
centroids : <class 'numpy.ndarray'>
[0, 0, 0, 1, 2, 3, 3, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
0 151


In [543]:
for i in range(20):
    centroids = calc_centroids(clusters, cluster_array)
    clusters = find_closest_centroid(centroids, cluster_array)
    cluster_var = np.mean(calc_SSE(clusters, cluster_array))
    cluster_vars.append(cluster_var)
    print(i+1, round(cluster_var))
print("final centroids ", centroids)
print("final clusters ", clusters)

1 32
2 25
3 20
4 19
5 19
6 19
7 19
8 18
9 18
10 18
11 18
12 18
13 18
14 18
15 18
16 18
17 18
18 18
19 18
20 18
final centroids  [array([4.71304348, 3.12173913, 1.4173913 , 0.19130435]), array([5.26153846, 3.67692308, 1.50769231, 0.29230769]), array([5.88360656, 2.74098361, 4.38852459, 1.43442623]), array([6.85384615, 3.07692308, 5.71538462, 2.05384615])]
final clusters  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 0, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 3, 2, 3, 3, 3, 3, 3, 2, 3, 2, 3, 2, 3, 3, 3, 3, 2, 2, 3, 3, 3, 2, 2, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
